In [8]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

Requirement already satisfied: python-woc in ./.venv/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in ./.venv/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in ./.venv/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in ./.venv/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in ./.venv/lib/python3.9/site-packages (from python-woc) (4.70.1)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in ./.venv/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.4)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.4)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.9/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: idna in ./.venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.20)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: anyio in ./.venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in ./.venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: zipp>=3.1.0 in ./.venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: typing_extensions>=4.5 in ./.venv/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.16.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in ./.venv/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.1)
WARNING: You are using pip version 21.3.1; however, version 26.0.1 is available.
You should consider upgrading via the '/home/bslessma/fdac26/MiniProject2/.venv/bin/python -m pip install --upgrade pip' command.

In [9]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
            'intelowlproject/IntelOwl',
            'intellistream/AllianceDB',
            'yesint/pteros',
            'cvnlab/analyzePRF',
            'simonfuhrmann/mve',
            'great-expectations/great_expectations',
            'google/grr',
            'projectcypress/cypress',
            'HyperHDG/HyperHDG',
            'MIT-SPARK/TEASER-plusplus'
            ]
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1                   project
0  0003ffda93da9378c9d9fe8dc0b13cc05a3b71e0  intelowlproject_intelowl

In [10]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  9%|▉         | 1218/12945 [20:49<3:21:29,  1.03s/it]

Got Errors {'14795024f24e3e3253e78e9a572698df7908eb71': 'Key 14795024f24e3e3253e78e9a572698df7908eb71 not found in /da5_fast/All.sha1c/commit_20.tch'}

 11%|█         | 1415/12945 [24:12<3:20:26,  1.04s/it]

Got Errors {'40112a43f6cf83cd7ce799344da4733aac174a27': 'Key 40112a43f6cf83cd7ce799344da4733aac174a27 not found in /da5_fast/All.sha1c/commit_64.tch'}

 11%|█▏        | 1464/12945 [25:03<3:16:46,  1.03s/it]

Got Errors {'7b8b26100256a85f91d28b0d2856271b58794410': 'Key 7b8b26100256a85f91d28b0d2856271b58794410 not found in /da5_fast/All.sha1c/commit_123.tch'}

 11%|█▏        | 1465/12945 [25:04<3:16:48,  1.03s/it]

Got Errors {'7d86744527fc6367b4023472584395bbc2743992': 'Key 7d86744527fc6367b4023472584395bbc2743992 not found in /da5_fast/All.sha1c/commit_125.tch'}

 36%|███▌      | 4602/12945 [1:19:11<2:23:21,  1.03s/it]

Got Errors {'4db91bab393eccdab3ed907cb89b36aef5e9652a': 'Key 4db91bab393eccdab3ed907cb89b36aef5e9652a not found in /da5_fast/All.sha1c/commit_77.tch'}

 42%|████▏     | 5398/12945 [1:32:55<2:09:44,  1.03s/it]

Got Errors {'620b058e3b8709d235e9b6b499bd76412a555b77': 'Key 620b058e3b8709d235e9b6b499bd76412a555b77 not found in /da5_fast/All.sha1c/commit_98.tch'}

 50%|█████     | 6522/12945 [1:52:18<1:51:23,  1.04s/it]

Got Errors {'7f06021b3a419b74992d3d196bbbb69a96228b1f': 'Key 7f06021b3a419b74992d3d196bbbb69a96228b1f not found in /da5_fast/All.sha1c/commit_127.tch'}

 53%|█████▎    | 6899/12945 [1:58:47<1:44:19,  1.04s/it]

Got Errors {'889c83f7d8933ab1770cec59e08d113b55d5e450': 'Key 889c83f7d8933ab1770cec59e08d113b55d5e450 not found in /da5_fast/All.sha1c/commit_8.tch'}

 57%|█████▋    | 7323/12945 [2:06:05<1:36:39,  1.03s/it]

Got Errors {'939c9f684ec1d231e393bb498dac938294cfadfc': 'Key 939c9f684ec1d231e393bb498dac938294cfadfc not found in /da5_fast/All.sha1c/commit_19.tch'}

 61%|██████    | 7916/12945 [2:16:18<1:26:45,  1.04s/it]

Got Errors {'a35f361220b3b6ab4fff5e4e6ac2e4b7cfb6b78e': 'Key a35f361220b3b6ab4fff5e4e6ac2e4b7cfb6b78e not found in /da5_fast/All.sha1c/commit_35.tch'}

 75%|███████▌  | 9723/12945 [2:47:25<55:17,  1.03s/it]

Got Errors {'d223fbb8ab74cd5f787f7762ee7a77a3806f47b7': 'Key d223fbb8ab74cd5f787f7762ee7a77a3806f47b7 not found in /da5_fast/All.sha1c/commit_82.tch'}

 78%|███████▊  | 10113/12945 [2:54:08<48:42,  1.03s/it]

Got Errors {'dbeee8cd584c3391c91e07b9b802d79f0d46990f': 'Key dbeee8cd584c3391c91e07b9b802d79f0d46990f not found in /da5_fast/All.sha1c/commit_91.tch'}

 85%|████████▌ | 11019/12945 [3:09:44<33:10,  1.03s/it]

Got Errors {'f36a2d2d3c32347c0509283d99e3a6040da37e01': 'Key f36a2d2d3c32347c0509283d99e3a6040da37e01 not found in /da5_fast/All.sha1c/commit_115.tch'}

 85%|████████▌ | 11048/12945 [3:10:14<32:35,  1.03s/it]

Got Errors {'f419c1f7e11d0fde51241dd165c16c6b0fc92fc9': 'Key f419c1f7e11d0fde51241dd165c16c6b0fc92fc9 not found in /da5_fast/All.sha1c/commit_116.tch'}

 88%|████████▊ | 11418/12945 [3:16:36<26:16,  1.03s/it]

Got Errors {'fdcaac36ded7fbb71a9cf48894b63646a124aef5': 'Key fdcaac36ded7fbb71a9cf48894b63646a124aef5 not found in /da5_fast/All.sha1c/commit_125.tch'}

 89%|████████▉ | 11495/12945 [3:17:56<25:02,  1.04s/it]

Got Errors {'ffd0cd21ab4fde63f4a7e4ea5a297403ce45ad19': 'Key ffd0cd21ab4fde63f4a7e4ea5a297403ce45ad19 not found in /da5_fast/All.sha1c/commit_127.tch'}

 89%|████████▉ | 11507/12945 [3:18:08<24:49,  1.04s/it]

Got Errors {'02568b866b39355769516016db322ebd2cc39b62': 'Key 02568b866b39355769516016db322ebd2cc39b62 not found in /da5_fast/All.sha1c/commit_2.tch'}

 91%|█████████ | 11717/12945 [3:21:45<21:09,  1.03s/it]

Got Errors {'a79cf7e697b254e63369592c91838f61dbb21e33': 'Key a79cf7e697b254e63369592c91838f61dbb21e33 not found in /da5_fast/All.sha1c/commit_39.tch'}

 91%|█████████ | 11734/12945 [3:22:03<20:47,  1.03s/it]

Got Errors {'b62afdaf24bdad437ceae9f4473fa4ecdb939d71': 'Key b62afdaf24bdad437ceae9f4473fa4ecdb939d71 not found in /da5_fast/All.sha1c/commit_54.tch'}

 91%|█████████ | 11735/12945 [3:22:04<20:47,  1.03s/it]

Got Errors {'b70c0b8b1efcab0ec227700e657c55462781fea6': 'Key b70c0b8b1efcab0ec227700e657c55462781fea6 not found in /da5_fast/All.sha1c/commit_55.tch'}

 91%|█████████ | 11737/12945 [3:22:06<20:43,  1.03s/it]

Got Errors {'b821f6014473273cdfc4d9fcf94c110250fc9d7e': 'Key b821f6014473273cdfc4d9fcf94c110250fc9d7e not found in /da5_fast/All.sha1c/commit_56.tch'}

 91%|█████████ | 11769/12945 [3:22:39<20:15,  1.03s/it]

Got Errors {'d0e06f82a6c3dd0bb96bc81d37f376570a2a34e7': 'Key d0e06f82a6c3dd0bb96bc81d37f376570a2a34e7 not found in /da5_fast/All.sha1c/commit_80.tch'}

 91%|█████████ | 11780/12945 [3:22:50<19:58,  1.03s/it]

Got Errors {'d9dc017e11b567f681b0a41f5b68ddc4a20e4c74': 'Key d9dc017e11b567f681b0a41f5b68ddc4a20e4c74 not found in /da5_fast/All.sha1c/commit_89.tch'}

 91%|█████████ | 11790/12945 [3:23:01<19:54,  1.03s/it]

Got Errors {'e13ae31af73905d16ff90037cada6ded6a579e76': 'Key e13ae31af73905d16ff90037cada6ded6a579e76 not found in /da5_fast/All.sha1c/commit_97.tch'}

 91%|█████████ | 11795/12945 [3:23:06<19:48,  1.03s/it]

Got Errors {'e59811f0de4ddd5cd9539437d6b4e8c48bab44bb': 'Key e59811f0de4ddd5cd9539437d6b4e8c48bab44bb not found in /da5_fast/All.sha1c/commit_101.tch'}

 91%|█████████ | 11806/12945 [3:23:17<19:34,  1.03s/it]

Got Errors {'ed990f6c24b35c81bb4b0362b9cba339c4f6d7fa': 'Key ed990f6c24b35c81bb4b0362b9cba339c4f6d7fa not found in /da5_fast/All.sha1c/commit_109.tch'}

 91%|█████████ | 11807/12945 [3:23:18<19:32,  1.03s/it]

Got Errors {'edbcf8ae9407d5e9df76b12aa49363146917d38d': 'Key edbcf8ae9407d5e9df76b12aa49363146917d38d not found in /da5_fast/All.sha1c/commit_109.tch', 'edee0806be0d3f6d670982a50f5f72985b300527': 'Key edee0806be0d3f6d670982a50f5f72985b300527 not found in /da5_fast/All.sha1c/commit_109.tch'}

 92%|█████████▏| 11856/12945 [3:24:09<18:47,  1.04s/it]

Got Errors {'086f32d17407cf94d05f65df4332fae5e5118ea3': 'Key 086f32d17407cf94d05f65df4332fae5e5118ea3 not found in /da5_fast/All.sha1c/commit_8.tch'}

 92%|█████████▏| 11882/12945 [3:24:36<18:17,  1.03s/it]

Got Errors {'1072a246986b60f236a174fd85393aec6c0a63bb': 'Key 1072a246986b60f236a174fd85393aec6c0a63bb not found in /da5_fast/All.sha1c/commit_16.tch'}

 92%|█████████▏| 11889/12945 [3:24:43<18:07,  1.03s/it]

Got Errors {'120824723dc6e42ce095f802ec918fd054ed350c': 'Key 120824723dc6e42ce095f802ec918fd054ed350c not found in /da5_fast/All.sha1c/commit_18.tch'}

 92%|█████████▏| 11897/12945 [3:24:51<18:04,  1.03s/it]

Got Errors {'143f68dd179ee1755facf0ff57357a5954fb72c3': 'Key 143f68dd179ee1755facf0ff57357a5954fb72c3 not found in /da5_fast/All.sha1c/commit_20.tch'}

 92%|█████████▏| 11904/12945 [3:24:58<17:51,  1.03s/it]

Got Errors {'163960797cfe28baebeaff1df72ea1261edb76bd': 'Key 163960797cfe28baebeaff1df72ea1261edb76bd not found in /da5_fast/All.sha1c/commit_22.tch'}

 92%|█████████▏| 11916/12945 [3:25:11<17:37,  1.03s/it]

Got Errors {'19b9dc5a18439cb7c9d05d1d25bf24b9e930a81e': 'Key 19b9dc5a18439cb7c9d05d1d25bf24b9e930a81e not found in /da5_fast/All.sha1c/commit_25.tch'}

 92%|█████████▏| 11937/12945 [3:25:32<17:24,  1.04s/it]

Got Errors {'1f35ceb43f0fbbb6ca9800536656a263c9042f43': 'Key 1f35ceb43f0fbbb6ca9800536656a263c9042f43 not found in /da5_fast/All.sha1c/commit_31.tch'}

 93%|█████████▎| 11995/12945 [3:26:32<16:15,  1.03s/it]

Got Errors {'32b3f162d72d5e125a590a97d02e1c5505a1d346': 'Key 32b3f162d72d5e125a590a97d02e1c5505a1d346 not found in /da5_fast/All.sha1c/commit_50.tch'}

 93%|█████████▎| 12016/12945 [3:26:54<15:56,  1.03s/it]

Got Errors {'38deca6e5a7a184a336cc40973df12179f78bb19': 'Key 38deca6e5a7a184a336cc40973df12179f78bb19 not found in /da5_fast/All.sha1c/commit_56.tch'}

 93%|█████████▎| 12023/12945 [3:27:01<15:50,  1.03s/it]

Got Errors {'3b3a406c02ba9c78c2eb518c43a00520a70f7a97': 'Key 3b3a406c02ba9c78c2eb518c43a00520a70f7a97 not found in /da5_fast/All.sha1c/commit_59.tch'}

 93%|█████████▎| 12034/12945 [3:27:13<15:36,  1.03s/it]

Got Errors {'3dd72be4d90b86fca36fc063978f8e0d579560a0': 'Key 3dd72be4d90b86fca36fc063978f8e0d579560a0 not found in /da5_fast/All.sha1c/commit_61.tch'}

 93%|█████████▎| 12037/12945 [3:27:16<15:35,  1.03s/it]

Got Errors {'3eca9c2670d2e5af38dc77139ed4da6d6b2ea9b1': 'Key 3eca9c2670d2e5af38dc77139ed4da6d6b2ea9b1 not found in /da5_fast/All.sha1c/commit_62.tch'}

 93%|█████████▎| 12040/12945 [3:27:19<15:33,  1.03s/it]

Got Errors {'3fc320b8d02413b83db53135d9787afb6a17e82d': 'Key 3fc320b8d02413b83db53135d9787afb6a17e82d not found in /da5_fast/All.sha1c/commit_63.tch'}

 94%|█████████▎| 12110/12945 [3:28:31<14:22,  1.03s/it]

Got Errors {'5525fdbb0ce3ff421d5610c006554920a1e1016d': 'Key 5525fdbb0ce3ff421d5610c006554920a1e1016d not found in /da5_fast/All.sha1c/commit_85.tch'}

 94%|█████████▎| 12116/12945 [3:28:37<14:15,  1.03s/it]

Got Errors {'564ea520e88a00686c5fe304abe43e3c656a4fa8': 'Key 564ea520e88a00686c5fe304abe43e3c656a4fa8 not found in /da5_fast/All.sha1c/commit_86.tch'}

 94%|█████████▍| 12136/12945 [3:28:58<13:51,  1.03s/it]

Got Errors {'5c5b4a974afc54de58c9f50a73c731e149375a7b': 'Key 5c5b4a974afc54de58c9f50a73c731e149375a7b not found in /da5_fast/All.sha1c/commit_92.tch'}

 94%|█████████▍| 12140/12945 [3:29:02<13:47,  1.03s/it]

Got Errors {'5d97bb86e7c29ec984671def282e283c14f23f87': 'Key 5d97bb86e7c29ec984671def282e283c14f23f87 not found in /da5_fast/All.sha1c/commit_93.tch'}

 94%|█████████▍| 12151/12945 [3:29:13<13:40,  1.03s/it]

Got Errors {'616aab6014b0bce3263e35cf55b004be9312d9c7': 'Key 616aab6014b0bce3263e35cf55b004be9312d9c7 not found in /da5_fast/All.sha1c/commit_97.tch'}

 94%|█████████▍| 12155/12945 [3:29:17<13:33,  1.03s/it]

Got Errors {'625fc9443ee7eccc1eb5286f2fbaf05d845fc3e9': 'Key 625fc9443ee7eccc1eb5286f2fbaf05d845fc3e9 not found in /da5_fast/All.sha1c/commit_98.tch'}

 94%|█████████▍| 12170/12945 [3:29:33<13:20,  1.03s/it]

Got Errors {'66bbe799e9bf7a1399ab89dc551092ed16a6a9ce': 'Key 66bbe799e9bf7a1399ab89dc551092ed16a6a9ce not found in /da5_fast/All.sha1c/commit_102.tch'}

 94%|█████████▍| 12175/12945 [3:29:38<13:13,  1.03s/it]

Got Errors {'681989ffabf8e4298fac15b7b17546e9029a6fb8': 'Key 681989ffabf8e4298fac15b7b17546e9029a6fb8 not found in /da5_fast/All.sha1c/commit_104.tch'}

 94%|█████████▍| 12182/12945 [3:29:45<13:09,  1.04s/it]

Got Errors {'69e42cc46f8a2241f1e155ccf517ef19af25cb63': 'Key 69e42cc46f8a2241f1e155ccf517ef19af25cb63 not found in /da5_fast/All.sha1c/commit_105.tch'}

 94%|█████████▍| 12183/12945 [3:29:46<13:08,  1.03s/it]

Got Errors {'6a5adaac275dfdcc4568207ec62a51a2a63a842f': 'Key 6a5adaac275dfdcc4568207ec62a51a2a63a842f not found in /da5_fast/All.sha1c/commit_106.tch'}

 94%|█████████▍| 12186/12945 [3:29:49<13:03,  1.03s/it]

Got Errors {'6b577a82f629a8c98a1274321aa433ac6bef8aa6': 'Key 6b577a82f629a8c98a1274321aa433ac6bef8aa6 not found in /da5_fast/All.sha1c/commit_107.tch'}

 94%|█████████▍| 12222/12945 [3:30:27<12:25,  1.03s/it]

Got Errors {'7703bb6de1ce5e0de65f5919d44b57a11b2f63fb': 'Key 7703bb6de1ce5e0de65f5919d44b57a11b2f63fb not found in /da5_fast/All.sha1c/commit_119.tch'}

 94%|█████████▍| 12227/12945 [3:30:32<12:23,  1.04s/it]

Got Errors {'780b8b8940fd173753ed629f095bf58a1f96e710': 'Key 780b8b8940fd173753ed629f095bf58a1f96e710 not found in /da5_fast/All.sha1c/commit_120.tch'}

 95%|█████████▍| 12235/12945 [3:30:40<12:12,  1.03s/it]

Got Errors {'7ab137dde05273e02dc2af0e61cc233ee73b8d83': 'Key 7ab137dde05273e02dc2af0e61cc233ee73b8d83 not found in /da5_fast/All.sha1c/commit_122.tch'}

 95%|█████████▍| 12237/12945 [3:30:42<12:10,  1.03s/it]

Got Errors {'7b39fab3840b9611ca95382b117f1d09842fbb9e': 'Key 7b39fab3840b9611ca95382b117f1d09842fbb9e not found in /da5_fast/All.sha1c/commit_123.tch'}

 95%|█████████▍| 12261/12945 [3:31:07<11:42,  1.03s/it]

Got Errors {'82e1e5d42fa0d912d9075b41983c9438a39558ab': 'Key 82e1e5d42fa0d912d9075b41983c9438a39558ab not found in /da5_fast/All.sha1c/commit_2.tch'}

 95%|█████████▌| 12323/12945 [3:32:11<10:40,  1.03s/it]

Got Errors {'96126b120f8ddd298605adec10396bdb884f10d2': 'Key 96126b120f8ddd298605adec10396bdb884f10d2 not found in /da5_fast/All.sha1c/commit_22.tch'}

 95%|█████████▌| 12329/12945 [3:32:17<10:31,  1.03s/it]

Got Errors {'97b334aa9ba655162048d5bd66d51ce2364159cc': 'Key 97b334aa9ba655162048d5bd66d51ce2364159cc not found in /da5_fast/All.sha1c/commit_23.tch'}

 95%|█████████▌| 12332/12945 [3:32:20<10:28,  1.03s/it]

Got Errors {'98d446ec9f672a6cd1d7d0f6ea4faea42847738e': 'Key 98d446ec9f672a6cd1d7d0f6ea4faea42847738e not found in /da5_fast/All.sha1c/commit_24.tch'}

 95%|█████████▌| 12341/12945 [3:32:29<10:23,  1.03s/it]

Got Errors {'9bbab2057a786b37a73d2a9afceb231d452572ea': 'Key 9bbab2057a786b37a73d2a9afceb231d452572ea not found in /da5_fast/All.sha1c/commit_27.tch'}

 95%|█████████▌| 12350/12945 [3:32:38<10:09,  1.03s/it]

Got Errors {'9eb1358f0190161c6c709d596099b0eb7a20060a': 'Key 9eb1358f0190161c6c709d596099b0eb7a20060a not found in /da5_fast/All.sha1c/commit_30.tch'}

 95%|█████████▌| 12356/12945 [3:32:44<10:05,  1.03s/it]

Got Errors {'a09de674654ebfff3f75313fceebc52f1a95a91d': 'Key a09de674654ebfff3f75313fceebc52f1a95a91d not found in /da5_fast/All.sha1c/commit_32.tch'}

 96%|█████████▌| 12368/12945 [3:32:57<09:52,  1.03s/it]

Got Errors {'a456afbcd2ee9469171d882c047bb2f6289cb5cd': 'Key a456afbcd2ee9469171d882c047bb2f6289cb5cd not found in /da5_fast/All.sha1c/commit_36.tch'}

 96%|█████████▌| 12401/12945 [3:33:31<09:18,  1.03s/it]

Got Errors {'add11faaee6837a1ea042bf66f088a91f8524973': 'Key add11faaee6837a1ea042bf66f088a91f8524973 not found in /da5_fast/All.sha1c/commit_45.tch'}

 96%|█████████▌| 12407/12945 [3:33:37<09:11,  1.03s/it]

Got Errors {'af5dc7f261377dee599292e9f7fa0d9efe2c8502': 'Key af5dc7f261377dee599292e9f7fa0d9efe2c8502 not found in /da5_fast/All.sha1c/commit_47.tch'}

 96%|█████████▋| 12470/12945 [3:34:42<08:08,  1.03s/it]

Got Errors {'c231b0d79b91b4a12d1df25a31e90e2566dd9365': 'Key c231b0d79b91b4a12d1df25a31e90e2566dd9365 not found in /da5_fast/All.sha1c/commit_66.tch'}

 96%|█████████▋| 12478/12945 [3:34:50<08:01,  1.03s/it]

Got Errors {'c493b8807f461e084ee1b694eebc9684f8beb5ae': 'Key c493b8807f461e084ee1b694eebc9684f8beb5ae not found in /da5_fast/All.sha1c/commit_68.tch', 'c4c62433cf2e36f2c02ce77ff0a07b30daae138d': 'Key c4c62433cf2e36f2c02ce77ff0a07b30daae138d not found in /da5_fast/All.sha1c/commit_68.tch'}

 96%|█████████▋| 12479/12945 [3:34:51<08:01,  1.03s/it]

Got Errors {'c4e562eae3f69c936a2afc1ca58b7f5b06037148': 'Key c4e562eae3f69c936a2afc1ca58b7f5b06037148 not found in /da5_fast/All.sha1c/commit_68.tch'}

 96%|█████████▋| 12483/12945 [3:34:55<07:54,  1.03s/it]

Got Errors {'c5dc94f72f814b6419fad37b8b09fed5dea9b907': 'Key c5dc94f72f814b6419fad37b8b09fed5dea9b907 not found in /da5_fast/All.sha1c/commit_69.tch'}

 96%|█████████▋| 12490/12945 [3:35:02<07:47,  1.03s/it]

Got Errors {'c7c457eb78acd92e191f68cff5daf4b6f830a2f6': 'Key c7c457eb78acd92e191f68cff5daf4b6f830a2f6 not found in /da5_fast/All.sha1c/commit_71.tch'}

 97%|█████████▋| 12498/12945 [3:35:10<07:38,  1.03s/it]

Got Errors {'c9ea0ee9cace797d85782414a07916277223f3d6': 'Key c9ea0ee9cace797d85782414a07916277223f3d6 not found in /da5_fast/All.sha1c/commit_73.tch'}

 97%|█████████▋| 12500/12945 [3:35:12<07:37,  1.03s/it]

Got Errors {'ca479fcb3cb711a777503fe74353d7e0c014c936': 'Key ca479fcb3cb711a777503fe74353d7e0c014c936 not found in /da5_fast/All.sha1c/commit_74.tch'}

 97%|█████████▋| 12504/12945 [3:35:17<07:33,  1.03s/it]

Got Errors {'cb802f7c01f0926e3812ae7e65a091c3a1a12b52': 'Key cb802f7c01f0926e3812ae7e65a091c3a1a12b52 not found in /da5_fast/All.sha1c/commit_75.tch'}

 97%|█████████▋| 12557/12945 [3:36:11<06:38,  1.03s/it]

Got Errors {'da16f3aeac40b92b74c900950bbb86629aff81a3': 'Key da16f3aeac40b92b74c900950bbb86629aff81a3 not found in /da5_fast/All.sha1c/commit_90.tch'}

 97%|█████████▋| 12609/12945 [3:37:04<05:45,  1.03s/it]

Got Errors {'e8be27e9aef6c4d39699d26a3d085bfbddf4e42a': 'Key e8be27e9aef6c4d39699d26a3d085bfbddf4e42a not found in /da5_fast/All.sha1c/commit_104.tch'}

 97%|█████████▋| 12621/12945 [3:37:17<05:33,  1.03s/it]

Got Errors {'ebcb3b607a35b8df929856f9b8917fe397ec1e43': 'Key ebcb3b607a35b8df929856f9b8917fe397ec1e43 not found in /da5_fast/All.sha1c/commit_107.tch'}

 98%|█████████▊| 12629/12945 [3:37:25<05:24,  1.03s/it]

Got Errors {'ee458678ef470f040e350dd18adb5950c7c1ddc1': 'Key ee458678ef470f040e350dd18adb5950c7c1ddc1 not found in /da5_fast/All.sha1c/commit_110.tch'}

 98%|█████████▊| 12676/12945 [3:38:13<04:36,  1.03s/it]

Got Errors {'fc7443622d5b8e4b1cbb2cc03fb8329dc46abeed': 'Key fc7443622d5b8e4b1cbb2cc03fb8329dc46abeed not found in /da5_fast/All.sha1c/commit_124.tch'}

 98%|█████████▊| 12686/12945 [3:38:24<04:26,  1.03s/it]

Got Errors {'ff2074df3a6ddf4a1259a6810b875a9436aecfc2': 'Key ff2074df3a6ddf4a1259a6810b875a9436aecfc2 not found in /da5_fast/All.sha1c/commit_127.tch'}

100%|██████████| 12945/12945 [3:42:52<00:00,  1.03s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0003ffda93da9378c9d9fe8dc0b13cc05a3b71e0,44f9608c756ec0b261c945130a440622f9752b5f,[096d5085a900a3ff03b86e0856dc35b1a595becf],a-rash <ashirrasheed96@gmail.com>,1675372411,+0400,a-rash <ashirrasheed96@gmail.com>,1675373255,+0400,fix: update code base to reflect change in tlp...,0003ffda93da9378c9d9fe8dc0b13cc05a3b71e0,intelowlproject_intelowl
1,000e0e7dea030138b58c620f37e307c5353c02ea,8baed47a846ef3906d27ae9c88ee123b6a945e83,[a5ea55eb255aa694bb4a49dcb1e14fa864ab933c],mlodic <30625432+mlodic@users.noreply.github.com>,1668081200,+0100,GitHub <noreply@github.com>,1668081200,+0100,Update api_app/analyzers_manager/observable_an...,000e0e7dea030138b58c620f37e307c5353c02ea,intelowlproject_intelowl

In [11]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '0003ffda93da9378c9d9fe8dc0b13cc05a3b71e0', 'tree': '44f9608c756ec0b261c945130a440622f9752b5f', 'parent': ['096d5085a900a3ff03b86e0856dc35b1a595becf'], 'author': 'a-rash <ashirrasheed96@gmail.com>', 'author_time': 1675372411, 'author_tz': '+0400', 'committer': 'a-rash <ashirrasheed96@gmail.com>', 'committer_time': 1675373255, 'committer_tz': '+0400', 'message': 'fix: update code base to reflect change in tlp standard (closes #1190)\n'}

In [12]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [13]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,mit-spark_teaser-plusplus,0003ffda93da9378c9d9fe8dc0b13cc05a3b71e0,a-rash <ashirrasheed96@gmail.com>,1675372411,fix: update code base to reflect change in tlp...

In [14]:
#mode a means append, so you have all your projects in the same file
yournetid='bslessma'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github